import { Geist, Geist_Mono, Exo_2 } from "next/font/google";
import "../../globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";



const exo2 = Exo_2({
  variable: "--font-Exo-2-sans",
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata = {
  title: "irchitDev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      {children}
    </>
  );
}
