import { Geist, Geist_Mono, Exo_2 } from "next/font/google";
import "./globals.css";


const exo2 = Exo_2({
  variable: "--font-Exo-2-sans",
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata = {
  title: "irchitDev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${exo2.variable}`}>
        {children}
      </body>
    </html>
  );
}
